/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/_/api/v2/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a SoundCloud permalink
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["resolveResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get tracks by IDs
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a track
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a playlist
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search resources
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["searchResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/search/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search tracks
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["searchTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/search/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search users
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/search/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search playlists
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["searchPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/search/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search querysuggestions
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["searchQuerySuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/mixed-selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get mixed selections
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getMixedSelections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/charts/selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get charts selections
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getChartsSelections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user tracks
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserTracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user playlists
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserPlaylists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/playlists_without_albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user playlists without albums
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserPlaylistsWithoutAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user albums
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user followers
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserFollowers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/followings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user followings
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserFollowings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user likes
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserLikes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/toptracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user toptracks
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserToptracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/relatedartists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user relatedartists
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserRelatedartists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/users/{id}/web-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user web profiles
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getUserWebProfiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/tracks/{id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get track related
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getTrackRelated"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/tracks/{id}/playlists_without_albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get track playlists without albums
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getTrackPlaylistsWithoutAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/tracks/{id}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get track albums
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getTrackAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/v2/tracks/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get track comments
         * @description Requires EnableAPI. Returns the unmodified upstream JSON, without Soundcloak frontend transformations or proxy-level caching. Query parameters pass through; incoming headers and body are discarded. Server-side authorization may be added when UseTokensInAPI is enabled. Upstream fields and parameters are not a stable public contract.
         */
        get: operations["getTrackComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get instance configuration
         * @description Registered only when InstanceInfo is enabled. Feature flags indicate which optional endpoints are available.
         */
        get: operations["getInstanceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/searchSuggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get search suggestions */
        get: operations["getSearchSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/rss/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get RSS feed for user tracks */
        get: operations["getUserRss"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/opensearch.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get OpenSearch discovery document */
        get: operations["getOpenSearchDescription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/proxy/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy a SoundCloud CDN image
         * @description Requires ProxyImages. Response content type comes from the CDN.
         */
        get: operations["proxyImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/hls/{author}/{track}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an HLS playlist
         * @description Rewrites playlist segment URLs through /_/proxy/hls. Defaults to HLSAudio. CDN URLs expire; Soundcloak renews cached stream URLs.
         */
        get: operations["getHlsPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/progressive/{author}/{track}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get progressive audio
         * @description Defaults to ProgressiveAudio. Supports MP3 or AAC depending on available transcodings; aac_hq prefers AAC, other values prefer MPEG.
         */
        get: operations["getProgressiveStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/restream/{author}/{track}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get audio with optional metadata
         * @description Requires Restream. Converts HLS to an audio stream or forwards progressive audio. Metadata injection and HLS conversion do not provide general byte-range support.
         */
        get: operations["getRestream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/restream/{author}/{track}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Redirect legacy restream URL
         * @deprecated
         * @description Requires Restream. Preserves the path and query string in the redirect to /_/api/restream/.
         */
        get: operations["legacyRestream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_/api/wv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy a Widevine license request
         * @description Registered only when ProxyStreams is enabled. Forwards the binary request body and query string to the SoundCloud Widevine license service; incoming headers are reset.
         */
        post: operations["getWidevineLicense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            kind?: string;
            username?: string;
            permalink?: string;
            permalink_url?: string;
            created_at?: string;
            last_modified?: string;
            full_name?: string;
            description?: string | null;
            avatar_url?: string | null;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            followers_count?: number;
            /** Format: int64 */
            followings_count?: number;
            /** Format: int64 */
            likes_count?: number;
            /** Format: int64 */
            playlist_count?: number;
            /** Format: int64 */
            track_count?: number;
            verified?: boolean;
        } & {
            [key: string]: unknown;
        };
        Transcoding: {
            url?: string;
            preset?: string;
            quality?: string;
            is_legacy_transcoding?: boolean;
            format?: {
                protocol?: string;
                mime_type?: string;
            } & {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /** @description Partial upstream track representation. Playlist entries may be ID-only stubs. Fields are optional and unknown upstream fields are preserved. */
        Track: {
            kind?: string;
            title?: string;
            permalink?: string;
            permalink_url?: string;
            created_at?: string;
            last_modified?: string;
            genre?: string;
            tag_list?: string;
            license?: string;
            policy?: string;
            track_authorization?: string;
            description?: string | null;
            artwork_url?: string | null;
            waveform_url?: string | null;
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            comment_count?: number;
            /** Format: int64 */
            likes_count?: number;
            /** Format: int64 */
            playback_count?: number;
            /** Format: int64 */
            reposts_count?: number;
            /**
             * Format: int64
             * @description Duration in milliseconds.
             */
            duration?: number;
            /**
             * Format: int64
             * @description Full duration in milliseconds.
             */
            full_duration?: number;
            user?: components["schemas"]["User"];
            media?: {
                transcodings?: components["schemas"]["Transcoding"][];
            } & {
                [key: string]: unknown;
            };
            publisher_metadata?: {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** @description Playlist or system-playlist. Tracks may contain only IDs; retrieve those with GET /_/api/v2/tracks?ids=... . */
        Playlist: {
            title?: string;
            kind?: string;
            permalink?: string;
            permalink_url?: string;
            created_at?: string;
            last_modified?: string;
            tag_list?: string;
            set_type?: string;
            id?: number | string;
            description?: string | null;
            artwork_url?: string | null;
            user?: components["schemas"]["User"];
            tracks?: components["schemas"]["Track"][];
            /** Format: int64 */
            track_count?: number;
            /** Format: int64 */
            likes_count?: number;
            /** Format: int64 */
            reposts_count?: number;
            is_album?: boolean;
        } & {
            [key: string]: unknown;
        };
        Comment: {
            /** Format: int64 */
            id?: number;
            kind?: string;
            body?: string;
            created_at?: string;
            /** @description Position in the track, in milliseconds. */
            timestamp?: number | null;
            user?: components["schemas"]["User"];
        } & {
            [key: string]: unknown;
        };
        /** @description Upstream resource; use kind to determine the resource type. Schemas intentionally allow partial objects. */
        Resource: components["schemas"]["Track"] | components["schemas"]["User"] | components["schemas"]["Playlist"];
        Selection: {
            kind?: string;
            title?: string;
            items?: components["schemas"]["ResourceCollection"];
        } & {
            [key: string]: unknown;
        };
        QuerySuggestion: {
            query?: string;
            output?: string;
        } & {
            [key: string]: unknown;
        };
        Like: {
            created_at?: string;
            track?: components["schemas"]["Track"];
            playlist?: components["schemas"]["Playlist"];
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        TrackCollection: {
            collection?: components["schemas"]["Track"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        UserCollection: {
            collection?: components["schemas"]["User"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        PlaylistCollection: {
            collection?: components["schemas"]["Playlist"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        CommentCollection: {
            collection?: components["schemas"]["Comment"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        ResourceCollection: {
            collection?: components["schemas"]["Resource"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        SelectionCollection: {
            collection?: components["schemas"]["Selection"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        QuerySuggestionCollection: {
            collection?: components["schemas"]["QuerySuggestion"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        /** @description Raw upstream collection. Pagination fields may be absent. next_href may point at SoundCloud; reuse its allowed path and query under this instance’s /_/api/v2 prefix. Do not send it to Soundcloak as an absolute URL. */
        LikeCollection: {
            collection?: components["schemas"]["Like"][];
            next_href?: string | null;
            /** Format: int64 */
            total_results?: number;
        } & {
            [key: string]: unknown;
        };
        Preferences: {
            Player?: string | null;
            ProxyStreams?: boolean | null;
            FullyPreloadTrack?: boolean | null;
            ProxyImages?: boolean | null;
            ParseDescriptions?: boolean | null;
            AutoplayNextTrack?: boolean | null;
            AutoplayNextRelatedTrack?: boolean | null;
            DefaultAutoplayMode?: string | null;
            HLSAudio?: string | null;
            RestreamAudio?: string | null;
            ProgressiveAudio?: string | null;
            DownloadAudio?: string | null;
            ShowAudio?: boolean | null;
            SearchSuggestions?: boolean | null;
            KeepPlayerFocus?: boolean | null;
            Waveform?: boolean | null;
            DRM?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        InstanceInfo: {
            DefaultPreferences: components["schemas"]["Preferences"];
            Commit: string;
            Repo: string;
            ProxyImages: boolean;
            ProxyStreams: boolean;
            Restream: boolean;
            GetWebProfiles: boolean;
            EnableAPI: boolean;
        } & {
            [key: string]: unknown;
        };
        /** @description Normally an array of strings. With format=opensearch, a tuple [original query, suggestions]. */
        Suggestions: string[] | [
            string,
            string[]
        ];
    };
    responses: {
        /** @description Error from Soundcloak or upstream. Body and content type vary; no stable JSON error schema is enforced. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
                "application/json": unknown;
                "text/html": string;
            };
        };
        /** @description Successful response */
        Response: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Track"][];
            };
        };
        /** @description Successful response */
        Response2: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TrackCollection"];
            };
        };
        /** @description Successful response */
        Response3: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UserCollection"];
            };
        };
        /** @description Successful response */
        Response4: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PlaylistCollection"];
            };
        };
        /** @description Successful response */
        Response5: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SelectionCollection"];
            };
        };
        /** @description Redirect; follow the Location header. */
        Response6: {
            headers: {
                /** @description Destination URL. */
                Location: string;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description No compatible transcoding available. */
        Response7: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Successful response */
        Response8: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "audio/mpeg": string;
                "audio/mp4": string;
            };
        };
    };
    parameters: {
        /** @description Optional override. The proxy inserts its current client_id when omitted. */
        client_id_query: string;
        /** @description SoundCloud resource identifier. */
        id_path: string;
        /** @description Search query. */
        q_query: string;
        /** @description Upstream page size; accepted limits depend on the endpoint. */
        limit_query: number;
        /** @description Upstream offset or cursor; preserve values from next_href. */
        offset_query: string;
        /** @description Forwarded to SoundCloud; support depends on the endpoint. */
        linked_partitioning_query: boolean;
        /** @description Optional raw JSON Preferences cookie, parsed by lib/preferences. Omitted fields use instance defaults. This is not an authentication cookie. */
        prefs_cookie: string;
        /** @description SoundCloud author permalink. */
        author_path: string;
        /** @description SoundCloud track permalink. */
        track_path: string;
        /** @description Preferred audio preset; actual format depends on availability, server credentials and fallback logic. Defaults to the relevant preference. */
        audio_query: "aac_hq" | "aac" | "mpeg" | "aac_lq";
        /** @description Byte range, e.g. bytes=0-1023. Supported only when forwarding a progressive stream without metadata injection. */
        Range_header: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resolveResource: {
        parameters: {
            query: {
                /** @description Full https://soundcloud.com/... permalink. */
                url: string;
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTracks: {
        parameters: {
            query: {
                /** @description Comma-separated track IDs. */
                ids: number[];
                /** @description Upstream result limit. */
                limit?: number;
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response"];
            default: components["responses"]["Error"];
        };
    };
    getTrack: {
        parameters: {
            query?: {
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Track"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getUser: {
        parameters: {
            query?: {
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getPlaylist: {
        parameters: {
            query?: {
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    searchResources: {
        parameters: {
            query: {
                /** @description Search query. */
                q: components["parameters"]["q_query"];
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceCollection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    searchTracks: {
        parameters: {
            query: {
                /** @description Search query. */
                q: components["parameters"]["q_query"];
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response2"];
            default: components["responses"]["Error"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                /** @description Search query. */
                q: components["parameters"]["q_query"];
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response3"];
            default: components["responses"]["Error"];
        };
    };
    searchPlaylists: {
        parameters: {
            query: {
                /** @description Search query. */
                q: components["parameters"]["q_query"];
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response4"];
            default: components["responses"]["Error"];
        };
    };
    searchQuerySuggestions: {
        parameters: {
            query: {
                /** @description Search query. */
                q: components["parameters"]["q_query"];
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuerySuggestionCollection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMixedSelections: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response5"];
            default: components["responses"]["Error"];
        };
    };
    getChartsSelections: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response5"];
            default: components["responses"]["Error"];
        };
    };
    getUserTracks: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response2"];
            default: components["responses"]["Error"];
        };
    };
    getUserPlaylists: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response4"];
            default: components["responses"]["Error"];
        };
    };
    getUserPlaylistsWithoutAlbums: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response4"];
            default: components["responses"]["Error"];
        };
    };
    getUserAlbums: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response4"];
            default: components["responses"]["Error"];
        };
    };
    getUserFollowers: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response3"];
            default: components["responses"]["Error"];
        };
    };
    getUserFollowings: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response3"];
            default: components["responses"]["Error"];
        };
    };
    getUserLikes: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeCollection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getUserToptracks: {
        parameters: {
            query?: {
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response"];
            default: components["responses"]["Error"];
        };
    };
    getUserRelatedartists: {
        parameters: {
            query?: {
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getUserWebProfiles: {
        parameters: {
            query?: {
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud user URN, e.g. soundcloud:users:420953284, as used by lib/sc/user.go. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": ({
                        url?: string;
                        title?: string;
                    } & {
                        [key: string]: unknown;
                    })[];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTrackRelated: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response2"];
            default: components["responses"]["Error"];
        };
    };
    getTrackPlaylistsWithoutAlbums: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response4"];
            default: components["responses"]["Error"];
        };
    };
    getTrackAlbums: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response4"];
            default: components["responses"]["Error"];
        };
    };
    getTrackComments: {
        parameters: {
            query?: {
                /** @description Upstream page size; accepted limits depend on the endpoint. */
                limit?: components["parameters"]["limit_query"];
                /** @description Upstream offset or cursor; preserve values from next_href. */
                offset?: components["parameters"]["offset_query"];
                /** @description Forwarded to SoundCloud; support depends on the endpoint. */
                linked_partitioning?: components["parameters"]["linked_partitioning_query"];
                /** @description Upstream sort order, e.g. newest. */
                sort?: string;
                /** @description Use 0 for the flat comment listing used by Cloudscape. */
                threaded?: number;
                /** @description Optional override. The proxy inserts its current client_id when omitted. */
                client_id?: components["parameters"]["client_id_query"];
            };
            header?: never;
            path: {
                /** @description SoundCloud resource identifier. */
                id: components["parameters"]["id_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentCollection"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getInstanceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSearchSuggestions: {
        parameters: {
            query: {
                /** @description Nonempty search query. */
                q: string;
                /** @description Return [query, suggestions] instead of a string array. */
                format?: "opensearch";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestions"];
                };
            };
            /** @description Missing or empty q. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getUserRss: {
        parameters: {
            query?: {
                /** @description Override preference when ProxyImages is enabled. */
                proxy_images?: boolean;
            };
            header?: never;
            path: {
                /** @description SoundCloud user permalink. */
                user: string;
            };
            cookie?: {
                /** @description Optional raw JSON Preferences cookie, parsed by lib/preferences. Omitted fields use instance defaults. This is not an authentication cookie. */
                prefs?: components["parameters"]["prefs_cookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/rss+xml": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOpenSearchDescription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/xml": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    proxyImage: {
        parameters: {
            query: {
                /** @description Image URL on a *.sndcdn.com host. */
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/*": string;
                };
            };
            /** @description Missing or rejected image URL. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getHlsPlaylist: {
        parameters: {
            query?: {
                /** @description Preferred audio preset; actual format depends on availability, server credentials and fallback logic. Defaults to the relevant preference. */
                audio?: components["parameters"]["audio_query"];
                /** @description Redirect to the expiring CDN playlist. */
                redirect?: boolean;
                /** @description Redirect segment requests to the CDN. Forced true when ProxyStreams is disabled. */
                redirect_parts?: boolean;
            };
            header?: never;
            path: {
                /** @description SoundCloud author permalink. */
                author: components["parameters"]["author_path"];
                /** @description SoundCloud track permalink. */
                track: components["parameters"]["track_path"];
            };
            cookie?: {
                /** @description Optional raw JSON Preferences cookie, parsed by lib/preferences. Omitted fields use instance defaults. This is not an authentication cookie. */
                prefs?: components["parameters"]["prefs_cookie"];
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpegurl": string;
                };
            };
            302: components["responses"]["Response6"];
            417: components["responses"]["Response7"];
            default: components["responses"]["Error"];
        };
    };
    getProgressiveStream: {
        parameters: {
            query?: {
                /** @description Preferred audio preset; actual format depends on availability, server credentials and fallback logic. Defaults to the relevant preference. */
                audio?: components["parameters"]["audio_query"];
                /** @description Redirect to the CDN. Forced true when ProxyStreams is disabled; otherwise false by default. */
                redirect?: boolean;
            };
            header?: {
                /** @description Byte range, e.g. bytes=0-1023. Supported only when forwarding a progressive stream without metadata injection. */
                Range?: components["parameters"]["Range_header"];
            };
            path: {
                /** @description SoundCloud author permalink. */
                author: components["parameters"]["author_path"];
                /** @description SoundCloud track permalink. */
                track: components["parameters"]["track_path"];
            };
            cookie?: {
                /** @description Optional raw JSON Preferences cookie, parsed by lib/preferences. Omitted fields use instance defaults. This is not an authentication cookie. */
                prefs?: components["parameters"]["prefs_cookie"];
            };
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response8"];
            /** @description Partial progressive audio from the CDN. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                    "audio/mp4": string;
                };
            };
            302: components["responses"]["Response6"];
            417: components["responses"]["Response7"];
            default: components["responses"]["Error"];
        };
    };
    getRestream: {
        parameters: {
            query?: {
                /** @description Preferred audio preset; actual format depends on availability, server credentials and fallback logic. Defaults to the relevant preference. */
                audio?: components["parameters"]["audio_query"];
                /** @description Inject track metadata. Uses DownloadAudio preference when true, otherwise RestreamAudio. */
                metadata?: boolean;
                /** @description Override title metadata; used only when metadata=true. */
                title?: string;
                /** @description Override genre metadata; used only when metadata=true. */
                genre?: string;
                /** @description Override author metadata; used only when metadata=true. */
                author?: string;
            };
            header?: {
                /** @description Byte range, e.g. bytes=0-1023. Supported only when forwarding a progressive stream without metadata injection. */
                Range?: components["parameters"]["Range_header"];
            };
            path: {
                /** @description SoundCloud author permalink. */
                author: components["parameters"]["author_path"];
                /** @description SoundCloud track permalink. */
                track: components["parameters"]["track_path"];
            };
            cookie?: {
                /** @description Optional raw JSON Preferences cookie, parsed by lib/preferences. Omitted fields use instance defaults. This is not an authentication cookie. */
                prefs?: components["parameters"]["prefs_cookie"];
            };
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Response8"];
            /** @description Partial audio when forwarding progressive audio without metadata. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": string;
                    "audio/mp4": string;
                };
            };
            417: components["responses"]["Response7"];
            default: components["responses"]["Error"];
        };
    };
    legacyRestream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SoundCloud author permalink. */
                author: components["parameters"]["author_path"];
                /** @description SoundCloud track permalink. */
                track: components["parameters"]["track_path"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            301: components["responses"]["Response6"];
            default: components["responses"]["Error"];
        };
    };
    getWidevineLicense: {
        parameters: {
            query: {
                /** @description License token returned by the upstream media endpoint. */
                license_token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Successful response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
