/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as UserRouteImport } from './routes/$user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91_Char93PreferencesRouteImport } from './routes/[_].preferences'
import { Route as UserTrackRouteImport } from './routes/$user_.$track'
import { Route as Char91_Char93PreferencesIndexRouteImport } from './routes/[_].preferences.index'
import { Route as Char91_Char93PreferencesThemeRouteImport } from './routes/[_].preferences.theme'
import { Route as Char91_Char93PreferencesInstanceRouteImport } from './routes/[_].preferences.instance'
import { Route as UserSetsPlaylistRouteImport } from './routes/$user_.sets.$playlist'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93PreferencesRoute =
  Char91_Char93PreferencesRouteImport.update({
    id: '/_/preferences',
    path: '/_/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserTrackRoute = UserTrackRouteImport.update({
  id: '/$user_/$track',
  path: '/$user/$track',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93PreferencesIndexRoute =
  Char91_Char93PreferencesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char91_Char93PreferencesRoute,
  } as any)
const Char91_Char93PreferencesThemeRoute =
  Char91_Char93PreferencesThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => Char91_Char93PreferencesRoute,
  } as any)
const Char91_Char93PreferencesInstanceRoute =
  Char91_Char93PreferencesInstanceRouteImport.update({
    id: '/instance',
    path: '/instance',
    getParentRoute: () => Char91_Char93PreferencesRoute,
  } as any)
const UserSetsPlaylistRoute = UserSetsPlaylistRouteImport.update({
  id: '/$user_/sets/$playlist',
  path: '/$user/sets/$playlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/search': typeof SearchRoute
  '/$user/$track': typeof UserTrackRoute
  '/_/preferences': typeof Char91_Char93PreferencesRouteWithChildren
  '/$user/sets/$playlist': typeof UserSetsPlaylistRoute
  '/_/preferences/instance': typeof Char91_Char93PreferencesInstanceRoute
  '/_/preferences/theme': typeof Char91_Char93PreferencesThemeRoute
  '/_/preferences/': typeof Char91_Char93PreferencesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/search': typeof SearchRoute
  '/$user/$track': typeof UserTrackRoute
  '/$user/sets/$playlist': typeof UserSetsPlaylistRoute
  '/_/preferences/instance': typeof Char91_Char93PreferencesInstanceRoute
  '/_/preferences/theme': typeof Char91_Char93PreferencesThemeRoute
  '/_/preferences': typeof Char91_Char93PreferencesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$user': typeof UserRoute
  '/search': typeof SearchRoute
  '/$user_/$track': typeof UserTrackRoute
  '/_/preferences': typeof Char91_Char93PreferencesRouteWithChildren
  '/$user_/sets/$playlist': typeof UserSetsPlaylistRoute
  '/_/preferences/instance': typeof Char91_Char93PreferencesInstanceRoute
  '/_/preferences/theme': typeof Char91_Char93PreferencesThemeRoute
  '/_/preferences/': typeof Char91_Char93PreferencesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$user'
    | '/search'
    | '/$user/$track'
    | '/_/preferences'
    | '/$user/sets/$playlist'
    | '/_/preferences/instance'
    | '/_/preferences/theme'
    | '/_/preferences/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$user'
    | '/search'
    | '/$user/$track'
    | '/$user/sets/$playlist'
    | '/_/preferences/instance'
    | '/_/preferences/theme'
    | '/_/preferences'
  id:
    | '__root__'
    | '/'
    | '/$user'
    | '/search'
    | '/$user_/$track'
    | '/_/preferences'
    | '/$user_/sets/$playlist'
    | '/_/preferences/instance'
    | '/_/preferences/theme'
    | '/_/preferences/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRoute
  SearchRoute: typeof SearchRoute
  UserTrackRoute: typeof UserTrackRoute
  Char91_Char93PreferencesRoute: typeof Char91_Char93PreferencesRouteWithChildren
  UserSetsPlaylistRoute: typeof UserSetsPlaylistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/preferences': {
      id: '/_/preferences'
      path: '/_/preferences'
      fullPath: '/_/preferences'
      preLoaderRoute: typeof Char91_Char93PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user_/$track': {
      id: '/$user_/$track'
      path: '/$user/$track'
      fullPath: '/$user/$track'
      preLoaderRoute: typeof UserTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/preferences/': {
      id: '/_/preferences/'
      path: '/'
      fullPath: '/_/preferences/'
      preLoaderRoute: typeof Char91_Char93PreferencesIndexRouteImport
      parentRoute: typeof Char91_Char93PreferencesRoute
    }
    '/_/preferences/theme': {
      id: '/_/preferences/theme'
      path: '/theme'
      fullPath: '/_/preferences/theme'
      preLoaderRoute: typeof Char91_Char93PreferencesThemeRouteImport
      parentRoute: typeof Char91_Char93PreferencesRoute
    }
    '/_/preferences/instance': {
      id: '/_/preferences/instance'
      path: '/instance'
      fullPath: '/_/preferences/instance'
      preLoaderRoute: typeof Char91_Char93PreferencesInstanceRouteImport
      parentRoute: typeof Char91_Char93PreferencesRoute
    }
    '/$user_/sets/$playlist': {
      id: '/$user_/sets/$playlist'
      path: '/$user/sets/$playlist'
      fullPath: '/$user/sets/$playlist'
      preLoaderRoute: typeof UserSetsPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char91_Char93PreferencesRouteChildren {
  Char91_Char93PreferencesInstanceRoute: typeof Char91_Char93PreferencesInstanceRoute
  Char91_Char93PreferencesThemeRoute: typeof Char91_Char93PreferencesThemeRoute
  Char91_Char93PreferencesIndexRoute: typeof Char91_Char93PreferencesIndexRoute
}

const Char91_Char93PreferencesRouteChildren: Char91_Char93PreferencesRouteChildren =
  {
    Char91_Char93PreferencesInstanceRoute:
      Char91_Char93PreferencesInstanceRoute,
    Char91_Char93PreferencesThemeRoute: Char91_Char93PreferencesThemeRoute,
    Char91_Char93PreferencesIndexRoute: Char91_Char93PreferencesIndexRoute,
  }

const Char91_Char93PreferencesRouteWithChildren =
  Char91_Char93PreferencesRoute._addFileChildren(
    Char91_Char93PreferencesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRoute,
  SearchRoute: SearchRoute,
  UserTrackRoute: UserTrackRoute,
  Char91_Char93PreferencesRoute: Char91_Char93PreferencesRouteWithChildren,
  UserSetsPlaylistRoute: UserSetsPlaylistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
