/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as UserIndexRouteImport } from './routes/$user/index'
import { Route as Char91_Char93PreferencesRouteRouteImport } from './routes/[_]/preferences/route'
import { Route as Char91_Char93PreferencesIndexRouteImport } from './routes/[_]/preferences/index'
import { Route as UserTrackIndexRouteImport } from './routes/$user/$track/index'
import { Route as Char91_Char93PreferencesThemeIndexRouteImport } from './routes/[_]/preferences/theme/index'
import { Route as Char91_Char93PreferencesInstanceIndexRouteImport } from './routes/[_]/preferences/instance/index'
import { Route as UserSetsPlaylistIndexRouteImport } from './routes/$user/sets/$playlist/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/$user/',
  path: '/$user/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93PreferencesRouteRoute =
  Char91_Char93PreferencesRouteRouteImport.update({
    id: '/_/preferences',
    path: '/_/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91_Char93PreferencesIndexRoute =
  Char91_Char93PreferencesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char91_Char93PreferencesRouteRoute,
  } as any)
const UserTrackIndexRoute = UserTrackIndexRouteImport.update({
  id: '/$user/$track/',
  path: '/$user/$track/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91_Char93PreferencesThemeIndexRoute =
  Char91_Char93PreferencesThemeIndexRouteImport.update({
    id: '/theme/',
    path: '/theme/',
    getParentRoute: () => Char91_Char93PreferencesRouteRoute,
  } as any)
const Char91_Char93PreferencesInstanceIndexRoute =
  Char91_Char93PreferencesInstanceIndexRouteImport.update({
    id: '/instance/',
    path: '/instance/',
    getParentRoute: () => Char91_Char93PreferencesRouteRoute,
  } as any)
const UserSetsPlaylistIndexRoute = UserSetsPlaylistIndexRouteImport.update({
  id: '/$user/sets/$playlist/',
  path: '/$user/sets/$playlist/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/_/preferences': typeof Char91_Char93PreferencesRouteRouteWithChildren
  '/$user/': typeof UserIndexRoute
  '/search/': typeof SearchIndexRoute
  '/$user/$track/': typeof UserTrackIndexRoute
  '/_/preferences/': typeof Char91_Char93PreferencesIndexRoute
  '/$user/sets/$playlist/': typeof UserSetsPlaylistIndexRoute
  '/_/preferences/instance/': typeof Char91_Char93PreferencesInstanceIndexRoute
  '/_/preferences/theme/': typeof Char91_Char93PreferencesThemeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$user': typeof UserIndexRoute
  '/search': typeof SearchIndexRoute
  '/$user/$track': typeof UserTrackIndexRoute
  '/_/preferences': typeof Char91_Char93PreferencesIndexRoute
  '/$user/sets/$playlist': typeof UserSetsPlaylistIndexRoute
  '/_/preferences/instance': typeof Char91_Char93PreferencesInstanceIndexRoute
  '/_/preferences/theme': typeof Char91_Char93PreferencesThemeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_/preferences': typeof Char91_Char93PreferencesRouteRouteWithChildren
  '/$user/': typeof UserIndexRoute
  '/search/': typeof SearchIndexRoute
  '/$user/$track/': typeof UserTrackIndexRoute
  '/_/preferences/': typeof Char91_Char93PreferencesIndexRoute
  '/$user/sets/$playlist/': typeof UserSetsPlaylistIndexRoute
  '/_/preferences/instance/': typeof Char91_Char93PreferencesInstanceIndexRoute
  '/_/preferences/theme/': typeof Char91_Char93PreferencesThemeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/_/preferences'
    | '/$user/'
    | '/search/'
    | '/$user/$track/'
    | '/_/preferences/'
    | '/$user/sets/$playlist/'
    | '/_/preferences/instance/'
    | '/_/preferences/theme/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$user'
    | '/search'
    | '/$user/$track'
    | '/_/preferences'
    | '/$user/sets/$playlist'
    | '/_/preferences/instance'
    | '/_/preferences/theme'
  id:
    | '__root__'
    | '/'
    | '/_/preferences'
    | '/$user/'
    | '/search/'
    | '/$user/$track/'
    | '/_/preferences/'
    | '/$user/sets/$playlist/'
    | '/_/preferences/instance/'
    | '/_/preferences/theme/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char91_Char93PreferencesRouteRoute: typeof Char91_Char93PreferencesRouteRouteWithChildren
  UserIndexRoute: typeof UserIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  UserTrackIndexRoute: typeof UserTrackIndexRoute
  UserSetsPlaylistIndexRoute: typeof UserSetsPlaylistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/': {
      id: '/$user/'
      path: '/$user'
      fullPath: '/$user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/preferences': {
      id: '/_/preferences'
      path: '/_/preferences'
      fullPath: '/_/preferences'
      preLoaderRoute: typeof Char91_Char93PreferencesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/preferences/': {
      id: '/_/preferences/'
      path: '/'
      fullPath: '/_/preferences/'
      preLoaderRoute: typeof Char91_Char93PreferencesIndexRouteImport
      parentRoute: typeof Char91_Char93PreferencesRouteRoute
    }
    '/$user/$track/': {
      id: '/$user/$track/'
      path: '/$user/$track'
      fullPath: '/$user/$track/'
      preLoaderRoute: typeof UserTrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_/preferences/theme/': {
      id: '/_/preferences/theme/'
      path: '/theme'
      fullPath: '/_/preferences/theme/'
      preLoaderRoute: typeof Char91_Char93PreferencesThemeIndexRouteImport
      parentRoute: typeof Char91_Char93PreferencesRouteRoute
    }
    '/_/preferences/instance/': {
      id: '/_/preferences/instance/'
      path: '/instance'
      fullPath: '/_/preferences/instance/'
      preLoaderRoute: typeof Char91_Char93PreferencesInstanceIndexRouteImport
      parentRoute: typeof Char91_Char93PreferencesRouteRoute
    }
    '/$user/sets/$playlist/': {
      id: '/$user/sets/$playlist/'
      path: '/$user/sets/$playlist'
      fullPath: '/$user/sets/$playlist/'
      preLoaderRoute: typeof UserSetsPlaylistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char91_Char93PreferencesRouteRouteChildren {
  Char91_Char93PreferencesIndexRoute: typeof Char91_Char93PreferencesIndexRoute
  Char91_Char93PreferencesInstanceIndexRoute: typeof Char91_Char93PreferencesInstanceIndexRoute
  Char91_Char93PreferencesThemeIndexRoute: typeof Char91_Char93PreferencesThemeIndexRoute
}

const Char91_Char93PreferencesRouteRouteChildren: Char91_Char93PreferencesRouteRouteChildren =
  {
    Char91_Char93PreferencesIndexRoute: Char91_Char93PreferencesIndexRoute,
    Char91_Char93PreferencesInstanceIndexRoute:
      Char91_Char93PreferencesInstanceIndexRoute,
    Char91_Char93PreferencesThemeIndexRoute:
      Char91_Char93PreferencesThemeIndexRoute,
  }

const Char91_Char93PreferencesRouteRouteWithChildren =
  Char91_Char93PreferencesRouteRoute._addFileChildren(
    Char91_Char93PreferencesRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char91_Char93PreferencesRouteRoute:
    Char91_Char93PreferencesRouteRouteWithChildren,
  UserIndexRoute: UserIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  UserTrackIndexRoute: UserTrackIndexRoute,
  UserSetsPlaylistIndexRoute: UserSetsPlaylistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
